Update 2_usecase.yml

diff --git a/.github/workflows/2_usecase.yml b/.github/workflows/2_usecase.yml
--- a/.github/workflows/2_usecase.yml
+++ b/.github/workflows/2_usecase.yml
@@ -52,7 +52,12 @@ jobs:
             exit 1
           fi
           
-          if ! cat "${page}" | grep -iq '](https://github.com/(moevm|user-attachments)/(blob/main/|assets/)?[^)]+)'; then 
+          if ! cat "${page}" then 
+            echo "::error::Предварительная проверка не пройдена - не найдено название страницы" 
+            exit 1
+          fi
+                    
+          if grep -iq '](https://github.com/(moevm|user-attachments)/(blob/main/|assets/)?[^)]+)'; then 
             echo "::error::Предварительная проверка не пройдена - не найдены изображения макета из репозитория. Вставьте их через \![Название картинки](полная ссылка вида https://github.com/moevm/ВАШ РЕПО/blob/main/assets/34864759/8f850ef1-fc3d-4adb-a7aa-81598cc7794c) . Если вы храните изображение макета где-то ВНЕ репозитория, то, пожалуйста, разместите файлы в репо - иначе потом очень сложно собирать материалы вашей проекта." 
             exit 1
           fi
